export const CREATIVE_CATEGORIES: { [key: string]: string[] } = {
  'Chủ đề': ['Ngẫu nhiên', 'Tình yêu', 'Chiến tranh', 'Hòa bình', 'Thiên nhiên', 'Không gian', 'Tương lai', 'Kỳ ảo', 'Thần thoại', 'Tan vỡ', 'Nổi loạn', 'Lễ hội'],
  'Giai điệu': ['Ngẫu nhiên', 'Đơn giản', 'Phức tạp', 'Bắt tai', 'Ám ảnh', 'Vút cao', 'Góc cạnh', 'Trữ tình', 'Dễ nhớ', 'Dân ca'],
  'Hòa âm': ['Ngẫu nhiên', 'Diatonic', 'Chromatic', 'Hòa hợp', 'Bất hòa', 'Phong phú', 'Thưa thớt', 'Chất Jazz', 'Atonal', 'Modal'],
  'Nhịp điệu': ['Ngẫu nhiên', 'Thôi thúc', 'Giật cục (Syncopated)', 'Đa nhịp điệu', 'Ổn định', 'Thư giãn', 'Groove phức tạp', 'Tối giản', 'Tempo nhanh'],
  'Cấu trúc': ['Ngẫu nhiên', 'Điệp khúc - Đoạn chính', 'AABA', 'Liên tục', 'Hình thức Sonatas', 'Rondo', 'Strophic', '12-bar blues'],
  'Nhạc cụ': ['Ngẫu nhiên', 'Dàn nhạc giao hưởng', 'Acoustic', 'Điện tử', 'Ban nhạc Rock', 'Bộ ba Jazz', 'Tối giản', 'A capella', 'Nhiều Synthesizer'],
  'Thể loại': ['Ngẫu nhiên', 'Pop', 'Rock', 'Jazz', 'Cổ điển', 'Hip-Hop', 'EDM', 'Dân ca', 'Blues', 'Metal', 'R&B', 'Đồng quê', 'Indie'],
  'Tâm trạng': ['Ngẫu nhiên', 'Vui vẻ', 'Buồn', 'Tức giận', 'Hy vọng', 'U sầu', 'Năng động', 'Yên bình', 'Sử thi', 'Huyền bí', 'Lãng mạn'],
  'Động lực học': ['Ngẫu nhiên', 'Mạnh dần (Crescendo)', 'Nhỏ dần (Diminuendo)', 'Thay đổi đột ngột', 'Chuyển biến tinh tế', 'Dải động rộng', 'Nén', 'To đều', 'Rất yên tĩnh'],
  'Sản xuất': ['Ngẫu nhiên', 'Lo-fi', 'Hi-fi', 'Sạch sẽ', 'Méo tiếng', 'Cổ điển (Vintage)', 'Hiện đại', 'Bóng bẩy', 'Thô mộc', 'Không gian', 'Trau chuốt'],
  'Sáng tạo': ['Ngẫu nhiên', 'Thử nghiệm', 'Thông thường', 'Ngẫu hứng', 'Đổi mới', 'Hoài niệm', 'Tiên phong (Avant-garde)', 'Kết hợp (Fusion)'],
  'Giọng hát': ['Ngẫu nhiên', 'Giọng khỏe (Belting)', 'Giọng giả thanh (Falsetto)', 'Thì thầm', 'Rap', 'Opera', 'Truyền cảm', 'Khàn', 'Trong trẻo', 'Đọc thơ', 'Hòa âm'],
};

export const CREATIVE_EXPLANATIONS: { [key: string]: { [key: string]: string } } = {
  'Giai điệu': {
    'Đơn giản': 'Một giai điệu dễ nghe, dễ nhớ, không có nhiều nốt phức tạp.',
    'Phức tạp': 'Giai điệu có nhiều biến tấu, nốt luyến láy và tiết tấu khó.',
    'Bắt tai': 'Giai điệu hấp dẫn, dễ dàng đi vào tâm trí người nghe.',
    'Ám ảnh': 'Giai điệu gợi cảm giác day dứt, khó quên, thường mang màu sắc u buồn.',
    'Vút cao': 'Giai điệu có những nốt cao, bay bổng, tạo cảm giác rộng lớn.',
    'Góc cạnh': 'Giai điệu có những bước nhảy quãng xa, tạo cảm giác mạnh mẽ, gai góc.',
    'Trữ tình': 'Giai điệu mềm mại, giàu cảm xúc, lãng mạn.',
    'Dễ nhớ': 'Tương tự như "Bắt tai", giai điệu mà người nghe có thể ngân nga theo ngay lập tức.',
    'Dân ca': 'Giai điệu mang âm hưởng của âm nhạc dân gian, truyền thống.',
  },
  'Hòa âm': {
    'Diatonic': 'Hòa âm dựa trên 7 nốt nhạc cơ bản của một gam, tạo cảm giác tự nhiên, quen thuộc.',
    'Chromatic': 'Sử dụng cả các nốt thăng/giáng ngoài gam, tạo ra màu sắc phức tạp, căng thẳng hơn.',
    'Hòa hợp': 'Các nốt nhạc kết hợp với nhau một cách êm ái, dễ chịu.',
    'Bất hòa': 'Các nốt nhạc tạo ra sự xung đột, căng thẳng, thường được dùng để tạo kịch tính.',
    'Phong phú': 'Hòa âm có nhiều lớp, sử dụng các hợp âm phức tạp (hợp âm 7, 9,...).',
    'Thưa thớt': 'Hòa âm đơn giản, chỉ sử dụng các hợp âm cơ bản, ít nhạc cụ.',
    'Chất Jazz': 'Sử dụng các hợp âm và tiến trình hòa âm đặc trưng của nhạc Jazz, tạo cảm giác tinh tế, ngẫu hứng.',
    'Atonal': 'Hòa âm không tuân theo một trung tâm âm nào, tạo cảm giác hỗn loạn, khó đoán.',
    'Modal': 'Hòa âm dựa trên các "mode" (thể) khác nhau của một gam, tạo ra các màu sắc độc đáo (ví dụ: Dorian, Phrygian).',
  },
  'Nhịp điệu': {
    'Thôi thúc': 'Nhịp điệu nhanh, mạnh mẽ, thúc giục người nghe hành động.',
    'Giật cục (Syncopated)': 'Nhấn vào các phách yếu hoặc giữa các phách, tạo ra sự bất ngờ và groove độc đáo.',
    'Đa nhịp điệu': 'Nhiều lớp nhịp điệu khác nhau được chơi cùng một lúc.',
    'Ổn định': 'Nhịp điệu đều đặn, dễ đoán, làm nền tảng vững chắc cho bài hát.',
    'Thư giãn': 'Nhịp điệu chậm, nhẹ nhàng, tạo cảm giác bình yên.',
    'Groove phức tạp': 'Sự kết hợp tinh vi giữa trống, bass và các nhạc cụ khác, tạo ra một nhịp điệu lôi cuốn, khó cưỡng.',
    'Tối giản': 'Nhịp điệu rất đơn giản, chỉ có vài yếu tố cơ bản.',
    'Tempo nhanh': 'Tốc độ bài hát nhanh, tràn đầy năng lượng.',
  },
  'Cấu trúc': {
    'Điệp khúc - Đoạn chính': 'Cấu trúc phổ biến nhất trong nhạc pop, gồm các đoạn chính (verse) và điệp khúc (chorus) lặp lại.',
    'AABA': 'Một cấu trúc bài hát gồm hai phần giống nhau (A), một phần khác biệt (B), và quay lại phần đầu (A).',
    'Liên tục': 'Bài hát phát triển liên tục không có sự lặp lại rõ ràng của các phần.',
    'Hình thức Sonatas': 'Một cấu trúc phức tạp trong nhạc cổ điển, gồm trình bày, phát triển và tái hiện chủ đề.',
    'Rondo': 'Một chủ đề chính (A) lặp lại xen kẽ với các chủ đề phụ khác (B, C,...).',
    'Strophic': 'Tất cả các đoạn thơ được hát với cùng một giai điệu.',
    '12-bar blues': 'Một tiến trình hợp âm gồm 12 ô nhịp, là nền tảng của nhạc Blues.',
  },
};
